# Generated by Django 4.2.30 on 2026-04-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LunchPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('restaurant', models.CharField(max_length=200)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('meal', models.CharField(choices=[('เช้า', 'เช้า'), ('กลางวัน', 'กลางวัน'), ('เย็น', 'เย็น'), ('ดึก', 'ดึก')], default='กลางวัน', max_length=20)),
                ('time', models.CharField(max_length=10)),
                ('slots', models.IntegerField(default=4)),
                ('joined', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
