# Generated by Django 4.2.30 on 2026-04-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_lunchpost_image_lunchpost_owner_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='ชื่อที่แสดงในโพสต์'),
        ),
    ]
