# Generated by Django 4.2.30 on 2026-04-21 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchpost',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
